key vault module in VNET
Energinet-DataHub/geh-terraform-modules pull request #33
Opened 2022-01-17 12:54 UTC by kristianschneider

This locks the KV to a private endpoint and requires a VNET
https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/142

2022-01-17 13:21 UTC, djorgensendk commented on azure/key-vault/main.tf
> +  }
Same comments as the PR regarding service bus:
- introduction of module for azurerm_private_endpoint
- dash after pe and psc in the names
- where we can find documentation of the possible values for subresource_names

2022-01-20 09:30 UTC, Renetnielsen requested changes
Great work, small comments nothing functional

2022-01-20 09:30 UTC, Renetnielsen commented on azure/key-vault/README.md
> +| `private_endpoint_subnet_id` | `string` | | **Required**  The ID of the private endpoint subnet
Add | after **Required** to push description to right box

2022-01-20 09:30 UTC, Renetnielsen commented on azure/key-vault/README.md
> +| `private_dns_zone_name` | `string` | | **Required**   The name of the private dns zone
Add | after **Required** to push description to right box

2022-01-20 09:30 UTC, Renetnielsen commented on azure/key-vault/main.tf
>  resource "null_resource" "dependency_setter" {
Just remove this entire block, its no longer used. Dependencies does not seem to be a problem in TF 1+

2022-01-20 10:45 UTC, merged