Feature/appinsight
Energinet-DataHub/geh-terraform-modules pull request #55
Opened 2022-02-15 14:16 UTC by jensone54

## Description

## References

https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/206
* #0000

2022-02-15 22:40 UTC, Renetnielsen requested changes

2022-02-15 22:40 UTC, Renetnielsen commented on azure/application-insights/main.tf
> +data "azurerm_log_analytics_workspace" "log_analytics_workspace" {
Instead of having to use a data resource, i would just pass in the log_analytics_workspace_id instead of the name. 
I think we can presume that if we can access the name we can also access the id.

So i would change this, and just use the workspace_id = var.workspace_id

2022-02-15 22:40 UTC, Renetnielsen commented on azure/application-insights/variables.tf
> +  description = "(Mandatory) Log workspace name"
~~(Mandatory)~~ -> (Required)

2022-02-16 07:05 UTC, jensone54 commented on azure/application-insights/main.tf
> +data "azurerm_log_analytics_workspace" "log_analytics_workspace" {
why is that a better solution? forces the user to do the same lookup

2022-02-16 07:08 UTC, jensone54 commented on azure/application-insights/main.tf
> +data "azurerm_log_analytics_workspace" "log_analytics_workspace" {
it of course allows the user to place the workspace in a different resource group

2022-02-16 07:31 UTC, merged