Add log analytics workspace to Vault
Energinet-DataHub/geh-terraform-modules pull request #56
Opened 2022-02-17 14:07 UTC by jensone54

## Description

Added log ananlytics workspace to key vault module

## References

[](https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/geh-terraform-modules/24)

* #0000

2022-02-17 14:32 UTC, djorgensendk requested changes

2022-02-17 14:32 UTC, djorgensendk commented on README.md
> -- [Azure Event Hub](./azure/eventhub-namespace)
the line concerning Event Hub shouldn't be remove, instead a new line with Log Analytics workspace should be added

2022-02-17 14:32 UTC, djorgensendk commented on azure/key-vault/README.md
> +| `log_analytics_workspace_id` | `string` | | **Required** | | Id of Log analytics workspace associated with the vault  |
this attribute should be added to the example under ##Usage as well

2022-02-17 14:32 UTC, djorgensendk commented on azure/key-vault/main.tf
> +  name               = "vault-log-analytics-diagnostic-setting"
Please make sure that the identation is the same

2022-02-17 14:32 UTC, djorgensendk commented on azure/key-vault/main.tf
> +    enabled  = false
This is the diagnostics log disabled?

2022-02-17 14:32 UTC, djorgensendk commented on azure/key-vault/variables.tf
> +  description = "(Required) The id of the log analytics workspace where the keyvault will log events (e.g. audit events)"
```suggestion
  description = "(Required) The ID of the Log Analytics workspace where the Key vault will log events (e.g. audit events)"
```

2022-02-17 14:37 UTC, jensone54 commented on README.md
> -- [Azure Event Hub](./azure/eventhub-namespace)
obviously not mistake

2022-02-17 14:38 UTC, jensone54 commented on azure/key-vault/README.md
> +| `log_analytics_workspace_id` | `string` | | **Required** | | Id of Log analytics workspace associated with the vault  |
actually it should go away will remove

2022-02-17 14:39 UTC, jensone54 commented on azure/key-vault/main.tf
> +    }
is that not retention for a deleted vault?

2022-02-17 14:58 UTC, djorgensendk commented on azure/key-vault/README.md
> +| `log_analytics_workspace_id` | `string` | | **Required** | | Id of Log analytics workspace associated with the vault  |
I don't understand why this variable should be removed

2022-02-18 07:13 UTC, jensone54 commented on azure/key-vault/README.md
> +| `log_analytics_workspace_id` | `string` | | **Required** | | Id of Log analytics workspace associated with the vault  |
it shouldn't I thought I had an output variablee , this one is staying

2022-02-18 07:20 UTC, jensone54 commented on azure/key-vault/main.tf
> +    enabled  = false
sorry thought is was referring to a property in the vault itself

2022-02-18 08:20 UTC, jensone54 commented on azure/key-vault/README.md
> +| `log_analytics_workspace_id` | `string` | | **Required** | | Id of Log analytics workspace associated with the vault  |
added to usage

2022-02-18 08:29 UTC, djorgensendk approved these changes

2022-02-18 08:39 UTC, merged