Add log workspace
Energinet-DataHub/geh-terraform-modules pull request #59
Opened 2022-02-25 11:14 UTC by jensone54

## Description

Adding Log Analytica Workspace to below resouexwa

## References

* https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/223
* https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/215
* https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/geh-shared-resources/156
* https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/214

2022-02-25 11:49 UTC, djorgensendk requested changes

2022-02-25 11:49 UTC, djorgensendk commented on azure/api-management/README.md
> +- Terraform version 1.1-5+
```suggestion
- Terraform version 1.1.5+
```

2022-02-25 11:49 UTC, djorgensendk commented on azure/api-management/main.tf
> +  }
Did you discuss with the architects what the length of the retention period should be?

2022-02-25 11:49 UTC, djorgensendk commented on azure/service-bus-namespace/variables.tf
> +  description = "(Required) The id of the Log Analytics Workspace where the SQL DB will log events (e.g. audit events)"
I suppose this variable is optional, due to the default value
```suggestion
  description = "(Optional) The id of the Log Analytics Workspace where the SQL DB will log events (e.g. audit events)"
```

2022-02-25 11:49 UTC, djorgensendk commented on azure/sql-database/variables.tf
> +  default = null
I guess the variable shouldn't have a default value when the variable is required

2022-02-25 12:09 UTC, jensone54 commented on azure/api-management/main.tf
> +  }
No 30 is a minimum and we can ask architects b4 using the modules

2022-02-25 12:09 UTC, jensone54 commented on azure/sql-database/variables.tf
> +  default = null
agree

2022-02-25 12:18 UTC, djorgensendk commented on azure/api-management/main.tf
> +  }
Could you then create a variable for the retention time so that we can decide when we use the module? Perhaps add a default value of 30

2022-02-25 12:42 UTC, dstsyst reviewed
Added a few comments.

2022-02-25 12:42 UTC, dstsyst commented on azure/api-management/README.md
> +- [Azure Monitor Diagnostic Setting](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources//monitor_diagnostic_setting)
Link is broken (I guess the // causes the issue)

2022-02-25 12:42 UTC, dstsyst commented on azure/mssql-database/README.md
> +- [Azure Monitor Diagnostic Setting](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources//monitor_diagnostic_setting)
Broken link

2022-02-25 12:42 UTC, dstsyst commented on azure/mssql-database/README.md
> +- AzureRM provider version 2.97.0+
Is it possible to use the same provider version in all modules?
Currently I have seen 2.94.0+ and here it is 2.97.0+

2022-02-25 12:42 UTC, dstsyst commented on azure/api-management/main.tf
> +
Notice the "ModuleVersion" in line 16 is "5.1.0" but it should be updated to match the next release "5.6.0" (as in the README).

2022-02-25 12:42 UTC, dstsyst commented on azure/mssql-server/README.md
> +- [Azure Monitor Diagnostic Setting](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources//monitor_diagnostic_setting)
Broken link

2022-02-25 12:42 UTC, dstsyst commented on azure/mssql-server/README.md
> +  log_analytics_workspace_id    = "example-log-analytics-workspace-id"
ref=5.4.0 on line 51 should be updated to use "5.6.0"

2022-02-25 12:42 UTC, dstsyst commented on azure/service-bus-namespace/variables.tf
> +  description = "(Optional) The id of the Log Analytics Workspace where the SQL DB will log events (e.g. audit events)"
```suggestion
  description = "(Optional) The id of the Log Analytics Workspace where the Service Bus will log events (e.g. audit events)"
```

2022-02-25 12:42 UTC, dstsyst commented on azure/service-bus-namespace/variables.tf
> +variable log_analytics_workspace_id {
I believe the README also needs to be updated?

2022-02-25 12:42 UTC, dstsyst commented on azure/sql-database/README.md
> +- [Azure Monitor Diagnostic Setting](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources//monitor_diagnostic_setting)
Broken link

2022-02-25 12:42 UTC, dstsyst commented on azure/sql-database/README.md
> +  name                        = "example-name"
Update "ref" version on line 41

2022-02-25 12:42 UTC, dstsyst commented on azure/sql-database/variables.tf
> +
Not sure that we need additional empty lines(?)

2022-02-25 12:42 UTC, dstsyst commented on azure/sql-database/variables.tf
> +
Remove empty line(?)

2022-02-25 12:47 UTC, jensone54 commented on azure/api-management/main.tf
> +  }
The value is in the log analytics module not in the individual modules

2022-03-04 11:10 UTC, jensone54 commented on azure/api-management/README.md
> +- Terraform version 1.1-5+
Changed to 1.1.5

2022-03-04 11:40 UTC, djorgensendk commented on azure/api-management/main.tf
> +  }
what about this variable: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_diagnostic_setting#days ?

2022-03-04 12:31 UTC, djorgensendk approved these changes

2022-03-17 08:51 UTC, closed without merging

2022-03-17 08:51 UTC, Renetnielsen commented
replaced by https://github.com/Energinet-DataHub/geh-shared-resources/pull/166