5.13.0 - add azurerm_api_management_api_diagnostic to api-management-api module
Energinet-DataHub/geh-terraform-modules pull request #70
Opened 2022-04-06 13:31 UTC by djorgensendk

2022-04-06 14:09 UTC, dstsyst reviewed
You forgot to update "ModuleVersion" to 5.13.0

2022-04-07 06:12 UTC, Renetnielsen requested changes

2022-04-07 06:12 UTC, Renetnielsen commented on azure/api-management-api/main.tf
> +  api_management_logger_id = var.apim_logger_id # azurerm_api_management_logger.apim_logger.id
Remove commented out stuff? We can always look at it through version control

2022-04-07 08:32 UTC, dstsyst approved these changes

2022-04-07 08:33 UTC, Renetnielsen approved these changes

2022-04-07 08:33 UTC, merged